name: Erlang CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches-ignore:
      - '**/**'

jobs:
  build:
    name: OTP-${{ matrix.otp }} Rebar-${{ matrix.rebar }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        otp: ['24', '26']
        rebar: ['3.20', '3.22']

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar }}

      - name: Info
        run: rebar3 --version

      - name: Compile debug
        run: rebar3 as debug compile

      # Clean here to get rid of the debug NIF lib
      - name: Clean
        run: rebar3 clean --all

      - name: Compile
        run: rebar3 as prod compile

      - name: XRef
        run: rebar3 as check xref

      - name: Dialyzer
        run: rebar3 as check dialyzer

      - name: Run tests with Erlang IO
        run: BITCASK_IO_MODE=erlang rebar3 eunit

      - name: Run tests with NIF IO
        run: BITCASK_IO_MODE=nif rebar3 eunit

      - name: Build docs
        run: rebar3 edoc
